# golangci-lint v2 configuration
# See: https://golangci-lint.run/usage/configuration/
version: "2"

run:
  timeout: 5m

linters:
  default: 'none'
  enable:
    - govet         # Standard Go vet checks
    - staticcheck   # Advanced static analysis
    - errcheck      # Check for unchecked errors
    - gosec         # Security-focused checks
    - dupl          # Code duplication detection
    - gocyclo       # Cyclomatic complexity
    - goconst       # Repeated strings that could be constants
    - misspell      # Spelling mistakes
    - unconvert     # Unnecessary type conversions
    - sloglint      # Structured logging consistency (log/slog)
    - unparam       # Unused function parameters

  settings:
    dupl:
      threshold: 100
    gocyclo:
      min-complexity: 30
    goconst:
      min-len: 3
      min-occurrences: 6
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (*os.File).Close
        # Cleanup operations where errors are non-critical
        - os.RemoveAll
        - os.Remove
        - os.MkdirAll
        - os.WriteFile
        - os.Chmod
        # Environment operations
        - os.Setenv
        - os.Unsetenv
        - os.Chdir
        # CLI output (rarely fails)
        - fmt.Fprintf
        - fmt.Fprintln

  exclusions:
    rules:
      # G304/G301/G306: aimgr is a file management tool. All file operations use
      # paths constructed internally from repo path, XDG directories, or tool
      # directory info — never from arbitrary user input.
      - path: '^pkg/'
        linters:
          - gosec
        text: 'G304|G301|G306'
      - path: '^cmd/'
        linters:
          - gosec
        text: 'G304|G301|G306'
      # Test helpers and integration tests use the same safe file patterns
      - path: '^test/'
        linters:
          - gosec
        text: 'G304|G301|G306'
      # G302: Log files and gitignore need 0644 permissions for readability
      - path: 'pkg/logging/logger\.go'
        linters:
          - gosec
        text: 'G302'
      - path: 'pkg/repo/manager\.go'
        linters:
          - gosec
        text: 'G302'
      # G115: term.GetSize/IsTerminal require int(fd) conversion; overflow is
      # not a practical concern for file descriptor values
      - path: 'pkg/output/terminal\.go'
        linters:
          - gosec
        text: 'G115'
      # G204: Git subprocess commands are constructed from internal repo paths
      # and manifest data, not arbitrary user input
      - path: 'pkg/repo/git\.go'
        linters:
          - gosec
        text: 'G204'
      - path: 'pkg/repo/manager\.go'
        linters:
          - gosec
        text: 'G204'
      - path: 'pkg/workspace/manager\.go'
        linters:
          - gosec
        text: 'G204'
      # Allow duplication in test files for table-driven test patterns
      - path: '_test\.go'
        linters:
          - dupl
      # Allow duplication in test helper files
      - path: 'test/'
        linters:
          - dupl
      # Test utility files (not _test.go) still use cleanup patterns where
      # error handling is non-critical (e.g., os.RemoveAll in cleanup funcs)
      - path: '^test/'
        text: 'G104:'
        linters:
          - gosec
      # Test functions are inherently complex (setup, table-driven, assertions);
      # enforcing cyclomatic complexity on tests hurts readability
      - path: '_test\.go'
        linters:
          - gocyclo
      - path: '^test/'
        linters:
          - gocyclo
      # Ignore certain gosec issues in tests
      - path: '_test\.go'
        text: 'G204:|G104:|G302:'
        linters:
          - gosec
      # LoadCommandWithBase is deprecated but still used internally until v2.0.0
      # migration replaces all callers with LoadCommand
      - text: 'SA1019:.*LoadCommandWithBase'
        linters:
          - staticcheck
      # Test files commonly repeat strings for setup/assertion; extracting to constants
      # hurts readability of table-driven tests
      - path: '_test\.go'
        linters:
          - goconst
      - path: '^test/'
        linters:
          - goconst
      # Output format names ("table", "json", "yaml") are used extensively in
      # CLI flag defaults, help text, and switch cases. They mirror the constants
      # in pkg/output/formatter.go but extracting every usage to a constant
      # would hurt readability of flag definitions and help strings.
      # The ".md" extension is a fundamental file type used across 30+ files.
      # "broken" is used as both resource.HealthBroken and as a VerifyIssue type.
      # Resource type names ("command", "skill", "agent") appear as typed constants
      # in pkg/resource/types.go but are also used as plain strings in switch cases,
      # slog keys, and display text throughout the codebase.
      - text: 'string `(table|json|yaml|\.md|broken|commands?|skills?|agents?)` has'
        linters:
          - goconst
