coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 1%
    patch:
      default:
        target: 60%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
